SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[deletedInvoiceDetail] (
		[ivh_hdrnumber]                 [int] NULL,
		[ivd_number]                    [int] NOT NULL,
		[stp_number]                    [int] NULL,
		[ivd_description]               [varchar](60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[cht_itemcode]                  [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_quantity]                  [float] NULL,
		[ivd_rate]                      [money] NULL,
		[ivd_charge]                    [money] NULL,
		[ivd_taxable1]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_taxable2]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_taxable3]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_taxable4]                  [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_unit]                      [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[cur_code]                      [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_currencydate]              [datetime] NULL,
		[ivd_glnum]                     [char](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ord_hdrnumber]                 [int] NULL,
		[ivd_type]                      [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_rateunit]                  [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_billto]                    [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_itemquantity]              [float] NULL,
		[ivd_subtotalptr]               [int] NULL,
		[ivd_allocatedrev]              [money] NULL,
		[ivd_sequence]                  [int] NULL,
		[ivd_invoicestatus]             [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[mfh_hdrnumber]                 [int] NULL,
		[ivd_refnum]                    [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[cmd_code]                      [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[cmp_id]                        [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_distance]                  [float] NULL,
		[ivd_distunit]                  [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_wgt]                       [float] NULL,
		[ivd_wgtunit]                   [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_count]                     [decimal](10, 2) NULL,
		[ivd_countunit]                 [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[evt_number]                    [int] NULL,
		[ivd_reftype]                   [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_volume]                    [float] NULL,
		[ivd_volunit]                   [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_orig_cmpid]                [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_payrevenue]                [money] NULL,
		[ivd_sign]                      [smallint] NULL,
		[ivd_length]                    [money] NULL,
		[ivd_lengthunit]                [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_width]                     [money] NULL,
		[ivd_widthunit]                 [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_height]                    [money] NULL,
		[ivd_heightunit]                [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_exportstatus]              [char](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[cht_basisunit]                 [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_remark]                    [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[tar_number]                    [int] NULL,
		[tar_tariffnumber]              [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[tar_tariffitem]                [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_fromord]                   [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_zipcode]                   [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_quantity_type]             [smallint] NULL,
		[cht_class]                     [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_mileagetable]              [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_charge_type]               [smallint] NULL,
		[ivd_trl_rent]                  [varchar](13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_trl_rent_start]            [datetime] NULL,
		[ivd_trl_rent_end]              [datetime] NULL,
		[ivd_rate_type]                 [smallint] NULL,
		[last_updateby]                 [varchar](256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[last_updatedate]               [datetime] NULL,
		[cht_lh_min]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[cht_lh_rev]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[cht_lh_stl]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[cht_lh_rpt]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[cht_rollintolh]                [int] NULL,
		[cht_lh_prn]                    [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[fgt_number]                    [int] NULL,
		[ivd_paylgh_number]             [int] NULL,
		[ivd_tariff_type]               [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_taxid]                     [varchar](15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_ordered_volume]            [decimal](18, 0) NULL,
		[ivd_ordered_loadingmeters]     [decimal](18, 0) NULL,
		[ivd_ordered_count]             [decimal](18, 0) NULL,
		[ivd_ordered_weight]            [decimal](18, 0) NULL,
		[ivd_loadingmeters]             [decimal](18, 0) NULL,
		[ivd_loadingmeters_unit]        [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_revtype1]                  [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_hide]                      [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_baserate]                  [decimal](19, 4) NULL,
		[ivd_rawcharge2]                [decimal](19, 4) NULL,
		[ivd_oradjustment]              [decimal](19, 4) NULL,
		[ivd_cbadjustment]              [decimal](19, 4) NULL,
		[ivd_fsc]                       [decimal](19, 4) NULL,
		[ivd_splitbillratetype]         [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_rawcharge]                 [decimal](19, 4) NULL,
		[ivd_bolid]                     [int] NULL,
		[ivd_shared_wgt]                [decimal](19, 4) NULL,
		[ivd_ARTaxAuth]                 [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_tollcost]                  [money] NULL,
		[ivd_paid_indicator]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_paid_amount]               [money] NULL,
		[ivd_miscmoney1]                [money] NULL,
		[ivd_actual_quantity]           [float] NULL,
		[ivd_actual_unit]               [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_tax_basis]                 [money] NULL,
		[ivd_billable_flag]             [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_post_invoice]              [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_loaded_distance]           [float] NULL,
		[ivd_empty_distance]            [float] NULL,
		[fgt_supplier]                  [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_showas_cmpid]              [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_ord_number]                [varchar](13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_leaseassetid]              [int] NULL,
		[ivd_MaskFromRating]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_car_key]                   [int] NULL,
		[ivd_allocated_quantity]        [float] NULL,
		[ivd_allocated_rate]            [money] NULL,
		[ivd_allocated_charge]          [money] NULL,
		[ivd_allocated_ivd_number]      [int] NULL,
		[dbsd_id_tariff]                [int] NULL,
		[ivd_allocation_type]           [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_allocated_qty]             [float] NULL,
		[ivd_reconcile_tariff]          [int] NULL,
		[ivd_comment]                   [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_transdate]                 [datetime] NULL,
		[ivd_ico_pyd_number_parent]     [int] NULL,
		[ivd_description_type]          [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_rated_qty]                 [float] NULL,
		[ivd_rated_rate]                [money] NULL,
		[dbst_rollinto_tar]             [int] NULL,
		[ivd_customer_char1]            [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_branch]                    [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_delays]                    [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[ivd_rate_factor]               [float] NULL
)
GO
ALTER TABLE [dbo].[deletedInvoiceDetail] SET (LOCK_ESCALATION = TABLE)
GO
